.gitignore
package-lock.json
package.json
pages/api/cep/v1/[cep].js

- Foi feito a habilitação do cors para o ZEIT, o mesmo foi testado e foi com sucesso
Issue de referencia: https://github.com/filipedeschamps/BrasilAPI/issues/9
Discussões sobre o cors foi feito no PR: https://github.com/filipedeschamps/BrasilAPI/pull/20

Habilitando o cors no endpoint cep

---

pages/api/cep/v1/[cep].js

Docs aqui 👉 [LINK](https://zeit.co/docs/v2/network/caching#stale-while-revalidate).
Basicamente, podemos usar a cache do ZEIT Now de maneira um pouco mais inteligente. O comportamente aqui é quase o mesmo do que apenas usar "s-maxage" mas sempre vamos garantir respostas rápidas a partir do primeiro request. Servimos o que a "cache tem" enquanto a plataforma revalida a informação no background.
Uso prático: https://zeit.co/blog/serverless-pre-rendering (depreciado em breve por iSSG https://notion-blog.now.sh/).

feat: usar "stale-while-revalidate" para "[cep].js"

---

.github/workflows/e2e-tests.yml
jest.config.js
package-lock.json
package.json
pages/api/status/v1/index.js
tests/cep-v1.test.js
tests/helpers/server.js

Pessoal, tudo bem? Segue minha proposta para suíte de testes do projeto. Mas antes, existem duas outras propostas: uma utilizando o Cypress https://github.com/filipedeschamps/BrasilAPI/pull/11 e outra integrando com o Travis CI https://github.com/filipedeschamps/BrasilAPI/pull/27
O objetivo desta proposta é disponibilizar uma suíte de testes que utiliza a combinação do **[Jest](https://jestjs.io/)** com o **[Github Actions](https://github.com/features/actions)**. O resultado esperado é, de uma forma simples, conseguir realizar testes locais utilizando o **servidor local** do Next.js e também testes remotos dentro do **CI** do Github utilizando a **Preview URL** disponibilizada pela Zeit (Now) que é uma URL única criada cada commit. Como bônus, o **CORS** é automaticamente testado pelo …

tests: adiciona suite de testes com Jest e Github Actions

---

README.md
graphql/modules/cep/index.js
graphql/modules/cep/resolvers.js
graphql/modules/cep/typeDefs.js
graphql/modules/status/index.js
graphql/modules/status/resolvers.js
graphql/modules/status/typeDefs.js
graphql/schema.js
package-lock.json
package.json
pages/api/cep/v1/[cep].js
pages/api/graphql/v1/index.js
pages/api/status/v1/index.js
tests/graphql-v1.test.js

Acredito que vai ajudar bastante quem quer usar graphql com essa api

Endpoint graphql

---

pages/api/cep/v1/[cep].js
pages/api/status/v1/index.js
tests/cep-v1.test.js

Cobre o primeiro dos itens sugeridos pelo @filipedeschamps no pr #29, adicionando semântica aos status code em caso de erros no endpoint `/cep/v1`.
Um problema que eu notei é que a API do cep-promise aceita letras como valor. Mesmo sabendo que é extremamente improvável que alguém vá fazer uma requisição dessas, isso não é um caso que deveria ser tratado? Usar letras aqui gera um `"service_error"`, porque o cep-promise ainda envia as requisições e os serviços dizem que não encontraram nada. O correto seria, na minha visão, retornar também um `"validation_error"` pra esse caso.
Como a BrasilAPI apenas captura as exceções lançadas pelo cep-promise e não faz validação, eu achei melhor não mexer nisso aqui agora. Acho que a mudança, se ela for mesmo absolutamente necessária, teria que ser …

feat: adiciona código de erro semântico em casos de ceps mal formatados

---

CONTRIBUTING.md
README.md
package.json
pages/index.js

This PR changes the links for the repository URL from [filipedeschamps/brasilAPI](http://github.com/filipedeschamps/brasilAPI) to link to the organization [brazilAPI/brazilAPI](https://github.com/BrasilAPI/BrasilAPI) on everyplace it's being linked.

fix: update repository URL

---

.github/workflows/e2e-tests.yml
jest.config.js
package.json
tests/cep-v1.test.js
tests/ddd-v1.test.js
tests/graphql-v1.test.js
tests/helpers/server/index.js
tests/helpers/server/setup.js
tests/helpers/server/teardown.js

Apesar da ideia de usar o Github actions testando contra uma URL real de um deployment da Vercel ser SENSACIONAL ela não estava funcionando corretamente sendo apenas possível ser acionada por colaboradores com escrita no repo original.
Para um projeto tradicional isso possivelmente seria o suficiente mas como estamos falando de um projeto open source em que o fluxo padrão é criar um fork e abrir um PR de um repo remoto para o original essa abordagem se mostrou mais problemática do que positiva.
Portanto a proposta é passar a testar contra um servidor local simplificando bastante o setup e a chance de problemas relativos ao setup dos forks.

Correção do fluxo de testes e CI

---

README.md

Adiciona um [invite](https://join.slack.com/t/brasilapi/shared_invite/zt-l12s2b8k-r0SHGZV4YZSMfrzhydn8WA) para o slack no readme
Closes #184

readme: add invite to slack

---

.github/workflows/e2e-tests.yml
README.md
sonar-project.properties

A análise do Sonar foi alterada pra opção SonarCloud Automatic Analysis, assim não temos problema de token quando o PR é feito a partir de um fork.

fix: change sonar analysis method

---

package-lock.json
package.json
pages/api/cep/v1/[cep].js
pages/docs/index.js
tests/cep-v1.test.js

Para melhorar a performance e a customização do endpoint de ceps atualizei para a versão `4.0.4` que permite um novo parâmetro contendo `providers` e esse não inclui o `brasilapi` como um possível provedor.
Obs: essa nova versão adiciona o campo `service` na resposta da consulta indicando de onde que foi encontrada a informação.
Obs2: aproveitei pra aumentar o cache de 1 pra 2 dias e atualizar um pouco os comentários.

Atualização da lib de ceps

---

README.md

Atualiza o Link do logo para a issue #186 
Como ainda não encontramos uma solução para gerar o invite do slack automágicamente, resolvi redirecionar o logo para a issue, que podemos editar o invite sem a necessidade de abrir PR's constantemente.

redirect slack logo to issue

---

README.md
pages/api/feriados/v1/[ano].js
pages/docs/doc.json
services/holidays/index.js
tests/feriados-v1.test.js

Olá pessoal, antes de fazer esse _pull request_ eu fiz um levantamento da situação desse recurso:
- O recurso foi solicitado nas _issues_ #68 e #118, nas duas ocasiões foram mencionados feriados nacionais e municipais.
- Existe três _pull requests_ para esse recurso em revisão: #121, #161 e #169 
As considerações feitas nesses PR estão relacionadas às limitações de acessar uma API externa, então optei por uma abordagem diferente.
No primeiro momento gerar uma lista apenas dos feriados nacionais, por ano. Existem alguns algoritmos para calcular os feriados móveis (Carnaval, Páscoa e Corpus Christi) e eles estão bem documentados na [wikipedia][computus]. Usando esses algoritmos é possível gerar a lista sem depender de um serviço externo.
Posteriormente pensamos em fornecer os feriados …

Cria endpoint de feriados nacionais

---

CONTRIBUTING.md
package-lock.json
package.json

Reference #199
Seguindo a thread original, foram inseridas ferramentas para padronizar as mensagens de commit do projeto.
1. Alterar um arquivo do projeto
2. Executar `git add` e `npm run commit` e ir escolhendo as opçoes e preencher os textos da CLI do commitzen.

feat(project): add commitzen standardize commit messages

---

pages/api/cnpj/v1/[cnpj].js
services/cnpj.js
tests/cnpj-v1.test.js

A partir da excelente discussão em #208, acabei mudando algumas coisas no [Minha Receita](https://minhareceita.org) (ainda não lançadas), que incluem:
* Busca por requisição GET, e não POST
* Retorno 404 para CNPJ não encontrado, e não 204
* Compatibilidade reversa com requisições POST utilizando redirecionamento com retorno 303
Com isso, nada quebra no BrasilAPI, mas seria legal atualizar para evitar redirecionamento e excluir código desnecessário. Não utilizei `v2` na estrutura pois:
* a Minha Receita (como projeto ainda em _beta_) não tem versionamento ainda
* as mudanças previstas oferecem compatibilidade reversa
* a API para os usuários do BrasilAPI não muda nada
O que acham?
Vou deixar como rascunho aqui até eu fazer o lançamento lá, assim vamos conversando sobre como manter esse …

Atualiza API para Minha Receita

---

services/fipe/price.js

Fix "Immediately return this expression instead of assigning it to the temporary variable 'result'" code smell

Fix code smell at getFipePrice function

---

services/holidays/index.js
tests/feriados-v1.test.js
tests/helpers/feriados/index.js

A implementação adiciona o feriado de sexta-feira santa a lista de feriados nacionais e que atende a [issue](https://github.com/BrasilAPI/BrasilAPI/issues/403).

feat: adiciona sexta-feira santa aos feriados nacionais

---

package-lock.json
package.json
pages/api/taxas/v1/[sigla].js
pages/api/taxas/v1/index.js
pages/docs/doc/taxas.json
tests/taxas-v1.test.js

Atualização do módulo `selic` para versão 1.0.0

refactor: update selic to v1.0.0

---

README.md

No PR anterior cometi um erro de digitação.

[fix] Typo no nome do .net

---

pages/api/ddd/v1/[ddd].js
pages/api/ibge/municipios/v1/[uf].js
pages/api/ibge/uf/v1/[code].js
pages/api/taxas/v1/[sigla].js
pages/docs/doc/ibge.json
tests/ibge-uf-v1.test.js

Olá! Fiz algumas padronizações pequenas para apis que usam a classe `NotFoundError`, dentre as minhas alterações estão:
- Padronização nas mensagens de erro para a api `ibge`
- Removido o status 404 sendo setado manualmente, a pŕopria exception já retorna o status correto
- Sugestão de melhoria em como a exception esta sendo disparada na api `ibge`, segui conforme demais APIs

Code improvements for not found errors

---

package-lock.json
package.json
pages/api/cep/v1/[cep].js
pages/api/cep/v2/[cep].js

Atualiza a biblioteca cep-promise para a versão 4.3.0 e adiciona o provedor `correios-alt`

Adiciona o provedor correios-alt

---

pages/docs/doc/basic_info.json

Enquanto estava fazendo os reviews notei que ao tentar copiar e colocar um link de path que tem na documentação todos eles iniciavam com brasilapi.com.br e por conta disso era necessário trocar o path manualmente. Com essa mudança isso não será mais necessário

refactor: renomeia nome do server para facilitar os reviews

---

package-lock.json
package.json
pages/api/pix/v1/participants.js
pages/docs/doc/pix.json
pages/index.js
pages/sitemap.xml/index.jsx
services/date.js
services/pix/participants.js
tests/pix-v1.test.js

- Lista de participantes do pix, incluindo o ISPB de cada IP
- Parse + Transform do CSV gerado pelo BCB
- Cache de 6 horas, pois não sei em qual horário é gerado o csv com os dados
- Dados dos participantes são gerados diariamente seguindo o padrão informado na #333 (https://www.bcb.gov.br/content/estabilidadefinanceira/spi/participantes-spi-${yyyyMMdd}.csv)
Relativo a #333 #464

Lista de participantes do pix

---

package-lock.json
package.json

essa atualização alteração altera o endereço de busca da widenet, de:
`https://ws.apicep.com/busca-cep/api/cep/:cep.json` para:
`https://cdn.apicep.com/file/apicep/:cep.json`

Atualiza a lib cep-promise para a versão 4.4.0

---

lib/fetchGeocoordinateFromBrazilLocation.js

A url da API nominatim.openstreetmap.org na função `fetchGeocoordinateFromBrazilLocation()` está retornando erro 500 devido a uma mudança no lado deles:

fix: fetchGeo API url

---

package-lock.json
pages/docs/doc/basic_info.json

Deixar o link de exemplo da API como dinâmico causava erros quando o usuário não entrava utilizando o caminho esperado.
Exemplo:
Se você entrar na documentação por [https://brasilapi.com.br/docs#operation/ondaspredictionwithoutdays(/cptec/v1/ondas/:cityCode)](https://[brasilapi.com.br/docs](https://brasilapi.com.br/docs#operation/ondaspredictionwithoutdays(/cptec/v1/ondas/:cityCode))#operation/ondaspredictionwithoutdays(/cptec/v1/ondas/:cityCode)) e clicar para ver o exemplo da URL completa de alguma rota, essa será sua visão:
Um exemplo que completamente incorreto.
Estudei  a documentação e cheguei a conclusão que não há opção senão utilizar uma URL fixa, visto que o domínio e rotas não mudam constantemente e essa dinamicidade só é aproveitada caso em algum ambiente de desenvolvimento.

Removendo URL dinâmica no exemplo da RequestURL

---

package-lock.json

simples atualização do package-lock para v2 e assim simplificar o review dos PRs que de modo não intencional mudaram para a v2

chore: update package lock to v2

---

services/sefaz/index.js

fix #583
#584
Pr para corrigir mudança de Json na api da Sefaz de ncm.

fix: fixed wrong json return from sefaz ncm api

---

services/holidays/index.js
tests/feriados-v1.test.js
tests/helpers/feriados/index.js

**Descrição**
A partir de 2024 o dia da consciência negra será considerado feriado nacional, pensando nisso fiz a inclusão do feriado a partir de 2024 no endpoint holidays.

Adiciona feriado nacional do dia da consciência negra a partir de 2024

---

pages/api/cep/v1/[cep].js
pages/api/cep/v2/[cep].js
pages/docs/doc/cep.json
services/cep/cep.js
tests/cep-v1.test.js
tests/cep-v2.test.js

Modifica a consulta de cep para priorizar dados vindos do open cep e assim evitar a consulta excessiva nos outros provedores.
Obs: localmente os testes estavam funcionando, pode ser algum bloqueio de IP

feat: adiciona open cep como fonte principal

---

lib/fetchGeocoordinateFromBrazilLocation.js
pages/docs/doc/cep.json

- corrige documentação
- adiciona tratamento de erro do open street map

refactor: tratamento erro cep v2

---

package-lock.json
package.json

A atualização da biblioteca `next-connect` causou o problema de cors, então mantive a versão antiga dela.

Corrige o problema de cors no upgrade pra node 20

---

app.js
package-lock.json
package.json

A versão 13.0.0 incluiu um comportamento que faz o next-connect retornar 404 sempre que todos os handlers da rota forem somente middlewares, o que fez nosso cors quebrar, visto que o options é tratado no middleware.
Commit relacionado: https://github.com/hoangvvo/next-connect/commit/edc99ddb7531dd399294158063cbfb2eb4fbe80d

Upgrade next_connect do version 0.12.1
