BrasilAPI/BrasilAPI

- package-lock.json
- package.json
Announcement: https://nextjs.org/blog/next-9-3
> Bump Next.js to 9.3

- .github/workflows/e2e-tests.yml
- README.md
- graphql/modules/cep/resolvers.js
- pages/api/cep/v1/[cep].js
[Anunciamos o rebrand!](https://vercel.com/blog/zeit-is-now-vercel)
> Mudar ZEIT para Vercel

- vercel.json
Diminuir os recursos da função para também diminuir os custos associados ao projeto.
Usando [essa configuração](https://vercel.com/blog/customizing-serverless-functions). Uma função é cobrada da seguinte forma:
```
mem_size (GB) * cpu_time (s) = total (GB-s)
```
Diminuindo a memória de uma função por 4, agora podemos rodar 4 vezes mais requests com o mesmo custo:
```
mem_size (GB) / 4 * cpu_time (s) = total * 4 (GB-s)
```
ou a mesma quantidade de requests com um custo 4 vezes menor.
Mais infos em https://aws.amazon.com/lambda/pricing/
> Create vercel.json with custom function memory

- README.md
Small correction for badge from e2e testing from personal(@filipedeschamps) to the organization (BrazilAPI).
> fix: correct badge from e2e testing

- README.md
- pages/api/banks/v1/[code].js
- pages/api/banks/v1/index.js
- services/banco-central.js
- tests/banks-v1.test.js
Resolves #78 
Tomei a liberdade de adicionar algumas coisas extras no projeto:
- Adicionar um ESLint
- Adicionar o arquivo `.editorconfig`
- Adicionei uma High Order Function que adiciona a feature de error handler às rotas. Dessa forma não precisamos ter tratamento de erros 500 em todas rotas. Fica tudo centralizado num lugar só.
- Adicionei um "middleware" de validação que usa o Joi. Quando há erro de validação ele automaticamente responde a request
- Adicionei Erros para a API bem como códigos de erro específicos além do código HTTP
- Mover os start/stop do servidor dos testes e2e para um só lugar, assim não precisamos ficar subindo/derrubando o server a cada teste
Qualquer dúvida e/ou sugestão, ou até crítica também, só falar 😄 
Se julgarem que alguma das coisas q fiz é _too much_ …
> Add banks routes

- .github/workflows/e2e-tests.yml
- .gitignore
- README.md
- jest.config.js
- sonar-project.properties
Esse PR adiciona a etapa de análise estática de código para termos visibilidade de qualidade do projeto. A análise vai ser realizada em todos os PRs.
O resultado pode ser visto em https://sonarcloud.io/dashboard?id=BrasilAPI_BrasilAPI
> CI: add sonar analysis

- .gitignore
- package-lock.json
- package.json
- pages/api/ddd/v1/[ddd].js
- pages/index.js
- tests/ddd-v1.test.js
Esse PR é uma reconstrução do PR #104 que tomei a liberdade atualizar a base e resolver os conflitos encontrados  (muitos 😅).
Como não tenho permissão de push no fork do @otaciliolacerda tomei a liberdade de recriar o PR dele.
> Corrige problemas listados pelo ESlint

- CODE_OF_CONDUCT.md
> add code of conduct proposal

- pages/docs/doc.json
Esse PR só adiciona um novo atributo nas docs pra corrigir a exibição delas.
> Correção pequena na definição das docs do CPNJ

- tests/cep-v2.test.js
@murilohns , modifiquei conforme proposto no pr #296
> Correção do teste do cep v2

- pages/index.js
Ajustando o logo da home no responsivo
> fix: ajusting reponsive image

- services/cnpj.js
Ainda tem um [_code smell_](https://sonarcloud.io/project/issues?id=BrasilAPI_BrasilAPI&open=AXnIknYFne3tTsFwR9ec&resolved=false&types=CODE_SMELL) que não foi corrigido na PR #311 e é super simples de arrumar.
> Corrige code smell

- pages/api/ibge/municipios/v1/[uf].js
- services/ibge.js
- tests/ibge-municipios-v1.test.js
Criação de um endpoint para consulta de municipios por estado, conforme sugerido na issue #267 .
> kiritokunkun: Consulta de municipios por estado

- tests/banks-v1.test.js
- tests/ibge-municipios-v1.test.js
Ajusta teste com bank code 260, requisição muda novo nome para o Nubank
> test(bank): ajusta teste com bank code 260

- pages/api/ibge/municipios/v1/[uf].js
- services/ibge/gov.js
> fix(ibge code): fix ibge code and standardizes the output

- package-lock.json
- package.json
- pages/api/ibge/municipios/v1/[uf].js
- services/dados-abertos-br/cities.js
Gostaria de utilizar o Promise.any para agilizar a resposta, mas não consegui, não sei se é alguma versão do node ou o que
> refactor(ibge): add another provider to IGBE Code

- services/banco-central/index.js
Foi realizado um refactor pois se caso tivesse algum erro na conversão csv para o json não iria retornar o fallback.
> refactor(banco-central): refactor the return banks data

- README.md
Adicionando no README as bibiliotecas criada pela comunidade para integrar com o BrasilApi.
Linguagens adicionadas: (Golang, JavaScript, Flutter)
Issues relacionadas: (#404, #338, #166)
> feat: adicionando bibliotecas da comunidade no README #404

- package-lock.json
- package.json
- pages/api/ibge/municipios/v1/[uf].js
- pages/docs/doc/ibge.json
- tests/helpers/server/setup.js
- tests/ibge-municipios-v1.test.js
Possibilita solicitar lista de provedores, seria possível utilizar uma query string `providers=gov, dados-abertos-br, wikipedia` Informando quais providers desejamos utilizar
Atualiza wikijs fix resolve #409
Para conseguir fazer o commit em meu ambiente precisei atualizar algumas libs.
> Possibilita solicitar lista de provedores

- README.md
Added .net client repository and author to BrasilAPI readme file.
> [chore] Added .net client to BrasilAPI

- README.md
python API client foi adicionado a documentação.
> doc: python API client

- README.md
Adicionando no README.md a lib do BrasilAPI para o Rust
> docs: Adicionando Rust Lib 

- README.md
Biblioteca criada para facilitar o acesso à API BrasilAPI na linguagem de programação Java.
> Added Java client to BrasilAPI

- README.md
Adiciona link na docmentação para biblioteca escrita em Delphi
> Link Biblioteca para Delphi

- README.md
Link to SDK PHP with the implementation of BrasilAPI endpoints
> docs: SDK for PHP

- README.md
Adicionando biblioteca PHP à lista
> Adicionando biblioteca PHP

- lib/fetchGeocoordinateFromBrazilLocation.js
- tests/cep-v2.test.js
- adiciona caso de teste
- refatora fetchGeocoordinateFromBrazilLocation para levar em consideração o número do cep
Close #470 #467
> fix: corrige geolocalização

- README.md
Added Vlang(V) client repository and author to BrasilAPI readme file.
```v
user_agent = 'v.http'
```
> Added Vlang(V) client to BrasilAPI

- middlewares/logger.js
- pages/api/cep/v1/[cep].js
> Bloqueio temporário

- CONTRIBUTING.md
- README.md
- tests/corretoras-v1.test.js
- tests/isbn-v1.test.js
Correct orthography and remove white space
> style(change readme and contributing file): change files

- README.md
Criação de um novo SDK para api BrasilApi utilizando golang. 
Nessa versão foi criada funções para consultas de **cep**, **cnpj**, **bancos**,  **cptec** e  **corretoras**. 
Futuramente estarei adicionando os outros endpoints.
> feat: adding new golang integration to README.md

- README.md
- Link no pub.dev: [br_api](https://pub.dev/packages/br_api)
- Link  no GitHub: [br_api_dart](https://github.com/PedroHAVeloso/br_api_dart)
> readme: adding new Flutter integration

- .eslintrc.js
- lib/fetchGeocoordinateFromBrazilLocation.js
- middlewares/logger.js
- pages/api/cep/v2/[cep].js
Atualiza rota cep v2 usando o padrão de middlewares e adicinando mais logs
> Atualiza rota cep v2 usando o padrão de middlewares e adicinando mais logs

- package.json
Atualiza lib cep-promise pra correção do provedor correios-alt
> Atualiza lib cep-promise pra correção do provedor correios-alt

- tests/cep-v1.test.js
- tests/cep-v2.test.js
- tests/cnpj-v1.test.js
- tests/corretoras-v1.test.js
- tests/ddd-v1.test.js
- tests/feriados-v1.test.js
- tests/fipe-v1.test.js
- tests/helpers/cors.js
- tests/ibge-municipios-v1.test.js
- tests/ibge-uf-v1.test.js
- tests/isbn-v1.test.js
- tests/ncm-v1.test.js
- tests/pix-v1.test.js
- tests/registrobr.test.js
- tests/taxas-v1.test.js
- cria teste de cors genérico
- utiliza teste de cors em todas as rotas
Rodando os testes a partir da branch atual
Rodando os testes do merge da branch atual + [fix/cors](https://github.com/BrasilAPI/BrasilAPI/pull/637)
> tests: adiciona testes de cors

- README.md
Add my Swift SPM library for Swift projects, Adding new features every day: https://github.com/LucasJorgeHubert/BrasilAPI-Swift
> change: Update README.md for new Swift SPM library

- lib/fetchGeocoordinateFromBrazilLocation.js
Adiciona timeout ao serviço nominatim de 2 segundos.
Relates to https://github.com/BrasilAPI/BrasilAPI/issues/693
> Adiciona timeout ao serviço nominatim
